// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table tick_data3 (timestamp:datetime, Symbol:string, Bid:long, Ask:long) 
.create-merge table tick_data1 (timestamp:string, Symbol:string, Bid:long, Ask:long, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table tick_data2 (timestamp:datetime, Symbol:real, Bid:long, Ask:long) 
